name: Go App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}

      # 4️⃣ Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t go-web-app:latest .
          docker tag go-web-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

      # 5️⃣ Deploy to EKS
      - name: Update Kubernetes Deployment
        env:
          KUBECONFIG: ${{ runner.temp }}/kubeconfig
        run: |
          # Decode kubeconfig secret to temporary file
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $KUBECONFIG

          # Update deployment image
          kubectl set image deployment/go-web-app \
            go-web-app=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

          # Optional: rollout status to ensure deployment succeeded
          kubectl rollout status deployment/go-web-app
